# Application Name
spring:
  application:
    name: basicspringsecuritydemousingdb

  # Datasource Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/tripbookingdb?createDatabaseIfNotExist=true
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT Configuration
jwtSecret: BLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURU
jwtExpirationMs: 86400000


web:
   cors:
     allowed-origins: "http://localhost:4200"
     allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
     allowed-headers: "*"
     allow-credentials: true
 